spring.application.name=med-clinica-api
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/med-clinica-api
spring.datasource.username=postgres
spring.datasource.password=developer
spring.jpa.hibernate.ddl-auto=update

JWT_SECRET=$(openssl rand -base64 32);
api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=med-clinica-api